name: Build and publish @cryptlex/lexactivator package

on:
  push:
    branches:
    - develop
    tags:
    - '3.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-2019]
        # os: [windows-2019]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm i -g node-pre-gyp
      - run: node-pre-gyp unpublish
      - name: Install Windows 2015 build tools
        if: matrix.os == 'windows-2019'
        run: npm install --global windows-build-tools --vs2015
      - run: npm i
      - run: npm run s3-publish
        env:
          node_pre_gyp_accessKeyId: ${{secrets.node_pre_gyp_accessKeyId}}
          node_pre_gyp_secretAccessKey: ${{secrets.node_pre_gyp_secretAccessKey}}
          node_pre_gyp_bucket: ${{secrets.node_pre_gyp_bucket}}
      - name: Build for windows x86
        if: matrix.os == 'windows-2019'
        run: npm i --target_arch=ia32
      - name: Publish windows x86
        if: matrix.os == 'windows-2019'
        run: npm run s3-publish --target_arch=ia32
        env:
          node_pre_gyp_accessKeyId: ${{secrets.node_pre_gyp_accessKeyId}}
          node_pre_gyp_secretAccessKey: ${{secrets.node_pre_gyp_secretAccessKey}}
          node_pre_gyp_bucket: ${{secrets.node_pre_gyp_bucket}}

  publish-npm:
    needs: build
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
