name: Build and publish @cryptlex/lexactivator package

on:
  push:
    branches:
    - develop
    tags:
    - '3.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-16.04, macos-latest, windows-2016]
        os: [windows-2016]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install Windows 2015 build tools
        if: matrix.os == 'windows-2016'
        run: npm install --global windows-build-tools --vs2015
      - run: npm i
      - run: npm run s3-publish

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      #- run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
