name: Build and publish @cryptlex/lexactivator package

on:
  push:
    tags:
    - '3.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, macos-latest, windows-2016]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: Setting Visual Studio version to 2015
        if: matrix.os == 'windows-2016'
        run: npm config set msvs_version 2015 --global
      - run: npm ci
      - run: npm run build-publish

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      #- run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
